services:
  - type: web
    name: key-value-cache-backend
    runtime: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        generateValue: true
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
